import requests, json
try:
    r = requests.get("http://localhost:5000/get_proactive_maintenance", timeout=10)
    d = r.json()
    print("success:", d.get("success"))
    s = d.get("summary", {})
    print("total_devices:", s.get("total_devices"))
    print("needs_attention:", s.get("needs_attention"))
    print("upcoming_warranty:", s.get("upcoming_warranty"))
    print("expired_warranty:", s.get("expired_warranty"))
    print("critical_open:", s.get("critical_open"))
    print("health_distribution:", d.get("health_distribution"))
    print("asset_health_count:", len(d.get("asset_health", [])))
    print("high_risk_count:", len(d.get("high_risk_assets", [])))
    print("lab_risk_count:", len(d.get("lab_risk", [])))
    print("timeline_count:", len(d.get("maintenance_timeline", [])))
    print("issues_by_age:", d.get("issues_by_age"))
    wa = d.get("warranty_alerts", {})
    print("warranty_expired:", len(wa.get("expired", [])))
    print("warranty_within_30:", len(wa.get("within_30", [])))
    print("warranty_within_60:", len(wa.get("within_60", [])))
    print("warranty_within_90:", len(wa.get("within_90", [])))
except Exception as e:
    print(f"Error: {e}")
